# Generated by Django 5.1.6 on 2025-02-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField()),
                ('positive_reviews', models.IntegerField()),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recetario_app.recipe')),
            ],
        ),
    ]
