# Generated by Django 5.1.6 on 2025-02-18 20:27
from tkinter.font import names

from django.db import migrations

from recetario_app.models import Chef, Restaurant


def poblar_chefs(apps, schema_editor):
    Chef = apps.get_model('recetario_app', 'Chef')
    Chef.objects.create(name='Gordon Ramsay', specialty='Cocina francesa')

def poblar_restaurantes(apps, schema_editor):
    Restaurant = apps.get_model('recetario_app', 'Restaurant')
    Restaurant.objects.create(name="Hell's Kitchen", location='Londres')
    Restaurant.objects.create(name="The Savoy Grill", location='Londres')

def poblar_recetas(apps, schema_editor):
    Recipe = apps.get_model('recetario_app', 'Recipe')
    Restaurant = apps.get_model('recetario_app', 'Restaurant')
    Chef = apps.get_model('recetario_app', 'Chef')

    gordon_ramsay = Chef.objects.get(name='Gordon Ramsay')

    # Crear la receta y guardarla en una variable para poder usarla después
    receta = Recipe.objects.create(title='Beef Wellington', preparation_time=120, chef=gordon_ramsay)

    hells_kitchen = Restaurant.objects.get(name="Hell's Kitchen")
    savoy_grill = Restaurant.objects.get(name="The Savoy Grill")

    # Añadir los restaurantes
    receta.restaurants.add(hells_kitchen, savoy_grill)



class Migration(migrations.Migration):

    dependencies = [
        ('recetario_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_chefs),
        migrations.RunPython(poblar_restaurantes),
        migrations.RunPython(poblar_recetas),
    ]
