# Generated by Django 5.1.6 on 2025-02-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario_app', '0002_recipestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField()),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recetario_app.restaurant')),
            ],
        ),
    ]
